### ISSUE TITLE
ModuleNotFoundError: No module named 'dlib'

### ISSUE THREAD

**Issue by farzadmohseni-ir** [mohsencyber/iraniancarlicenseplate#1]
**Although all libraries are installed , errors are seen when Run .**

**If possible , fix it or explain it so I can fix it .**

https://stackoverflow.com/questions/52829483/importerror-no-module-named-dlib

![Annotation 2021-03-09 215655](https://user-images.githubusercontent.com/57835828/110520702-10776d00-8124-11eb-96e0-231ff92412e1.jpg)

![Annotation 2021-03-09 220611](https://user-images.githubusercontent.com/57835828/110520717-15d4b780-8124-11eb-9c0a-545c183925a4.jpg)

**Comment by mohsencyber** [comment]
I think you should install dlib for Python 3.
pip3 install dlib
Or get the dlib source from its site and build it with cmake.

**Comment by imHarry404** [comment]
![error](https://user-images.githubusercontent.com/60144420/227702049-bc13cd67-9ea0-4dd4-b5ef-ebf079ea2486.png)
Getting this error.

**Comment by Satish8124** [comment]
use this command
conda install -c conda-forge dlib
